name: Docs

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e '.[docs]'
    - name: Build docs
      run: |
        sphinx-build -W -b html docs docs/build/html
